apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hgxy8dgau-nodejs 
  janus-idp.io/tekton: hgxy8dgau-nodejs
  backstage.io/kubernetes-id: hgxy8dgau-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hgxy8dgau-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml